/** Synthetic M92 images: explicit RGB/alpha samples, never customer artwork. */
import { PDFDocument, PDFName, type PDFRef } from 'pdf-lib';
import jpeg from 'jpeg-js';

export const RGB = Uint8Array.from([
  255, 0, 0, 0, 255, 0, 0, 0, 255, 255, 255, 0, 0, 255, 255, 255, 0, 255,
]);
export const ALPHA = Uint8Array.from([0, 85, 170, 255, 128, 64]);
export const OTHER_ALPHA = Uint8Array.from([255, 170, 85, 0, 64, 128]);
// Synthetic sRGB profile generated with Pillow ImageCms.createProfile('sRGB') / LittleCMS.
export const SRGB_PROFILE = Uint8Array.from(
  Buffer.from(
    'AAACTGxjbXMEQAAAbW50clJHQiBYWVogB+oACQAMAAkAFQAzYWNzcE1TRlQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZGVzYwAAAQgAAAA2Y3BydAAAAUAAAABMd3RwdAAAAYwAAAAUY2hhZAAAAaAAAAAsclhZWgAAAcwAAAAUYlhZWgAAAeAAAAAUZ1hZWgAAAfQAAAAUclRSQwAAAggAAAAgZ1RSQwAAAggAAAAgYlRSQwAAAggAAAAgY2hybQAAAigAAAAkbWx1YwAAAAAAAAABAAAADGVuVVMAAAAaAAAAHABzAFIARwBCACAAYgB1AGkAbAB0AC0AaQBuAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAADAAAAAcAE4AbwAgAGMAbwBwAHkAcgBpAGcAaAB0ACwAIAB1AHMAZQAgAGYAcgBlAGUAbAB5WFlaIAAAAAAAAPbWAAEAAAAA0y1zZjMyAAAAAAABDEIAAAXe///zJQAAB5MAAP2Q///7of///aIAAAPcAADAblhZWiAAAAAAAABvoAAAOPUAAAOQWFlaIAAAAAAAACSfAAAPhAAAtsNYWVogAAAAAAAAYpcAALeHAAAY2XBhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbY2hybQAAAAAAAwAAAACj1wAAVHsAAEzNAACZmgAAJmYAAA9c',
    'base64',
  ),
);
// Lossless 3x2 RGB fixture generated by Pillow/OpenJPEG 2.5.4 from RGB above.
// Regenerate: Image.new('RGB',(3,2)); putdata(the six RGB tuples); save(format='JPEG2000',irreversible=False).
export const JP2 = Uint8Array.from(
  Buffer.from(
    'AAAADGpQICANCocKAAAAFGZ0eXBqcDIgAAAAAGpwMiAAAAAtanAyaAAAABZpaGRyAAAAAgAAAAMAAwcHAAAAAAAPY29scgEAAAAAABAAAADDanAyY/9P/1EALwAAAAAAAwAAAAIAAAAAAAAAAAAAAAMAAAACAAAAAAAAAAAAAwcBAQcBAQcBAf9SAAwAAAABAAEEBAAB/1wAB0BASEhQ/2QAJQABQ3JlYXRlZCBieSBPcGVuSlBFRyB2ZXJzaW9uIDIuNS40/5AACgAAAAAASAAB/5PPtAwLtrHPtAgCy9+AGApzDM/ACn4AcPtAQAZ/CvRKCc/ABn4AcPtAQAMDh1QJwBDPwAo/ABADAocA/9k=',
    'base64',
  ),
);

export function rgbaOf(
  rgb: Uint8Array,
  alpha = new Uint8Array(rgb.length / 3).fill(255),
): Uint8Array {
  const rgba = new Uint8Array(alpha.length * 4);
  for (let i = 0; i < alpha.length; i++) {
    rgba.set(rgb.subarray(i * 3, i * 3 + 3), i * 4);
    rgba[i * 4 + 3] = alpha[i] ?? 0;
  }
  return rgba;
}

export async function embeddedFixture(): Promise<{ bytes: Uint8Array; jpegBytes: Uint8Array }> {
  const pdf = await PDFDocument.create();
  const context = pdf.context;
  const jpegBytes = Uint8Array.from(
    jpeg.encode({ width: 3, height: 2, data: rgbaOf(RGB) }, 100).data,
  );
  const mask = (alpha: Uint8Array): PDFRef =>
    context.register(
      context.flateStream(alpha, {
        Type: 'XObject',
        Subtype: 'Image',
        Width: 3,
        Height: 2,
        BitsPerComponent: 8,
        ColorSpace: 'DeviceGray',
      }),
    );
  const aMask = mask(ALPHA);
  const bMask = mask(OTHER_ALPHA);
  const image = (maskRef: PDFRef, filter?: string, data = RGB): PDFRef => {
    const dict = {
      Type: 'XObject',
      Subtype: 'Image',
      Width: 3,
      Height: 2,
      BitsPerComponent: 8,
      ColorSpace: 'PictureRGB',
      SMask: maskRef,
    };
    return context.register(
      filter ? context.stream(data, { ...dict, Filter: filter }) : context.flateStream(data, dict),
    );
  };
  const a = image(aMask);
  const b = image(bMask);
  const jpg = image(aMask, 'DCTDecode', jpegBytes);
  const jp2 = image(aMask, 'JPXDecode', JP2);
  // Inner form inherits Outer resources; both occurrences retain their own image masks.
  const inner = context.register(
    context.flateStream('q 3 0 0 2 0 0 cm /A Do Q q 3 0 0 2 4 0 cm /B Do Q', {
      Type: 'XObject',
      Subtype: 'Form',
      BBox: [0, 0, 10, 10],
      Matrix: [5, 0, 0, 5, 0, 0],
    }),
  );
  const outer = context.register(
    context.flateStream('/Inner Do', {
      Type: 'XObject',
      Subtype: 'Form',
      BBox: [0, 0, 100, 100],
      Resources: { XObject: { Inner: inner, A: a, B: b }, ColorSpace: { PictureRGB: 'DeviceRGB' } },
    }),
  );
  const resources = context.obj({
    XObject: {
      A: a,
      B: b,
      J: jpg,
      JP: jp2,
      Outer: outer,
      Unused: image(mask(new Uint8Array(6).fill(1))),
    },
    ColorSpace: { PictureRGB: 'DeviceRGB' },
    ExtGState: { Fade: { Type: 'ExtGState', ca: 0.2 } },
  });
  const page = pdf.addPage([600, 600]);
  page.node.set(PDFName.of('Resources'), resources);
  page.node.set(
    PDFName.of('Contents'),
    context.register(
      context.flateStream(
        [
          'q 1 1 1 1 re W n /Fade gs 6 0 0 4 10 20 cm /A Do Q',
          'q 0 12 -6 0 100 100 cm /A Do Q',
          'q 30 4 7 20 100 120 cm /B Do Q',
          'q 24 0 0 16 40 40 cm /J Do Q',
          'q 24 0 0 16 80 40 cm /JP Do Q',
          'q 4 0 0 4 150 150 cm /Outer Do Q',
        ].join('\n'),
      ),
    ),
  );
  const second = pdf.addPage([600, 600]);
  second.node.set(PDFName.of('Resources'), resources);
  second.node.set(
    PDFName.of('Contents'),
    context.register(context.flateStream('q 0.3 0 0 0.2 0 0 cm /A Do Q')),
  );
  return { bytes: await pdf.save({ useObjectStreams: false }), jpegBytes };
}
