/**
 * Extracts the interface strings into `resources/i18n/en-GB.json`, then generates every
 * spelling-variant catalogue from it (M130).
 *
 * ```
 * node scripts/extract-i18n.ts            # rewrite the catalogues
 * node scripts/extract-i18n.ts --check    # fail if they are out of date (npm run lint, CI)
 * ```
 *
 * It reads `t('key', 'English')` call sites in `src/**` — both arguments plain string literals,
 * which is why `t()` is documented as requiring them. A `t(` whose key is not a literal cannot be
 * read statically and is *reported*, not silently skipped: a string that never reaches the
 * catalogue is a string that can never be translated.
 *
 * Variants are generated, never written by hand. `resources/i18n/spelling-<id>.json` holds
 * whole-word replacements; only the entries the table actually changes are written out, so
 * `en-US.json` is a short list of differences and `t()` falls back to en-GB for the rest.
 *
 * The matching and re-spelling live in `scripts/lib/i18n-extract.ts` so they can be unit-tested
 * without a file system — the same split as `check-styles.ts` and `style-rules.ts`.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { catalogueJson, extractStrings, spellingVariant } from './lib/i18n-extract.ts';

const ROOT = process.cwd();
const SOURCE_DIRS = ['src'];
const I18N_DIR = join(ROOT, 'resources', 'i18n');
const SOURCE_LANGUAGE = 'en-GB';
const SKIP_DIRS = new Set(['node_modules', 'out', 'dist', 'release', 'coverage']);
const EXTENSIONS = ['.ts', '.tsx'];

function* walk(dir: string): Generator<string> {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) yield* walk(full);
    else if (EXTENSIONS.some((ext) => name.endsWith(ext))) yield full;
  }
}

interface SpellingTable {
  readonly words: Readonly<Record<string, string>>;
}

const check = process.argv.includes('--check');
const strings: Record<string, string> = {};
const clashes: string[] = [];
let suspects = 0;
let files = 0;

for (const dir of SOURCE_DIRS) {
  for (const file of walk(join(ROOT, dir))) {
    files++;
    const where = relative(ROOT, file).replace(/\\/g, '/');
    const result = extractStrings(readFileSync(file, 'utf8'), where);
    suspects += result.suspects;
    for (const entry of result.found) {
      const existing = strings[entry.key];
      if (existing !== undefined && existing !== entry.text) {
        clashes.push(`${entry.key}: "${existing}" vs "${entry.text}" (${entry.where})`);
      }
      strings[entry.key] = entry.text;
    }
  }
}

const written: string[] = [];
const stale: string[] = [];

function write(name: string, text: string): void {
  const path = join(I18N_DIR, name);
  let current: string;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    // No catalogue yet: the first run writes one.
    current = '';
  }
  if (current === text) return;
  if (check) stale.push(name);
  else {
    writeFileSync(path, text);
    written.push(name);
  }
}

write(
  `${SOURCE_LANGUAGE}.json`,
  catalogueJson(
    SOURCE_LANGUAGE,
    strings,
    'Generated by `node scripts/extract-i18n.ts` from the t() call sites in src/. Do not edit by hand: change the English at the call site and run the script again.',
  ),
);

for (const name of readdirSync(I18N_DIR)) {
  const match = /^spelling-([a-z]{2}-[A-Z]{2})\.json$/.exec(name);
  if (!match) continue;
  const language = match[1] ?? '';
  const table = JSON.parse(readFileSync(join(I18N_DIR, name), 'utf8')) as SpellingTable;
  write(
    `${language}.json`,
    catalogueJson(
      language,
      spellingVariant(strings, table.words),
      `Generated by \`node scripts/extract-i18n.ts\` by applying ${name} to ${SOURCE_LANGUAGE}.json. Only the strings that differ are listed; the rest fall back to ${SOURCE_LANGUAGE}. Do not edit by hand.`,
    ),
  );
}

if (clashes.length > 0) {
  console.error(`extract-i18n: ${String(clashes.length)} key(s) used with two different texts:`);
  for (const clash of clashes) console.error(`  ${clash}`);
  process.exit(1);
}
if (suspects > 0) {
  console.warn(
    `extract-i18n: ${String(suspects)} t() call(s) whose key is not a plain string literal — those strings cannot be translated`,
  );
}
if (check && stale.length > 0) {
  console.error(
    `extract-i18n: ${stale.join(', ')} out of date. Run \`node scripts/extract-i18n.ts\`.`,
  );
  process.exit(1);
}
console.info(
  `extract-i18n: ${String(Object.keys(strings).length)} string(s) from ${String(files)} files` +
    (written.length > 0 ? `; wrote ${written.join(', ')}` : '; catalogues already current'),
);
